### ISSUE TITLE
`equatorial` should also be true if inclination is π

### ISSUE THREAD

**Issue by Alseidon** [smcardle14/OrbitalElements.jl#6]
If `i=π`, then the orbit is also equatorial, with a negative angular momentum.

**Comment by Alseidon** [comment]
Following this: the conditions `evec[2] < 0` and `rvec[2]` in the equatorial cases should be multiplied by `cos(i)`, to account for the "reversed" equatorial cases.

**Comment by smcardle14** [comment]
Thanks for the feedback!  I updated the logic to handle the retrograde equatorial case in commit 75209c3c44807812cb793829cf49966bbd56f9ba
